# Generated by Django 4.2.7 on 2023-11-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_view_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
